# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
  
  end

  desc "beta"
  lane :beta do
    Dir.chdir('../app')
    pa = Dir.pwd
    file = pa + "/" + ENV["MYAPP_RELEASE_STORE_FILE"]
    gradle(
      task: "clean assembleRelease",
      properties: {
        'android.injected.signing.store.file' => file,
        'android.injected.signing.store.password' => ENV["MYAPP_RELEASE_STORE_PASSWORD"],
        'android.injected.signing.key.alias' => ENV["MYAPP_RELEASE_KEY_ALIAS"],
        'android.injected.signing.key.password' => ENV["MYAPP_RELEASE_KEY_PASSWORD"]
      }
    )

    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    supply(
      apk: apk_path,
      track: "alpha",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
      )

  end
end
